controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
logout:
    path: /logout
    methods: GET
login2:
    path:       /login2/{nomuser}/{password}
    controller: App\Controller\LoginController::index2
    methods:    GET
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
    prefix:   /sg